// ─── CREATED: extracted from test.jsx ────────────────────────
// ─── EDITED: added nav + tab styles for Viewer feature ───────

export const styles = {
  root: {
    minHeight: "100vh",
    background: "#0f172a",
    color: "#e2e8f0",
    fontFamily: "'Inter', system-ui, sans-serif",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    borderBottom: "1px solid #1e293b",
    padding: "16px 32px",
  },
  headerInner: {
    display: "flex",
    alignItems: "center",
    gap: 20,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  logoIcon: {
    fontSize: 22,
    color: "#4f8ef7",
  },
  logoText: {
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: "-0.5px",
    color: "#f1f5f9",
  },
  tagline: {
    margin: 0,
    fontSize: 12,
    color: "#64748b",
    letterSpacing: "0.05em",
  },
  main: {
    display: "flex",
    gap: 24,
    padding: "24px 32px",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  sidebar: {
    width: 220,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  sidebarTitle: {
    margin: 0,
    fontSize: 13,
    fontWeight: 600,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    paddingBottom: 8,
    borderBottom: "1px solid #1e293b",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "14px 0",
    borderBottom: "1px solid #1e293b",
  },
  sectionTitle: {
    margin: 0,
    fontSize: 11,
    fontWeight: 600,
    color: "#4f8ef7",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    cursor: "default",
  },
  inputLabel: {
    fontSize: 12,
    color: "#94a3b8",
  },
  inputRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  input: {
    flex: 1,
    background: "#1e293b",
    border: "1px solid #334155",
    borderRadius: 6,
    color: "#f1f5f9",
    fontSize: 13,
    padding: "5px 8px",
    outline: "none",
    width: "100%",
  },
  unit: {
    fontSize: 11,
    color: "#64748b",
    minWidth: 20,
  },
  hint: {
    margin: 0,
    fontSize: 11,
    color: "#475569",
    fontStyle: "italic",
  },
  summary: {
    background: "#1e293b",
    borderRadius: 8,
    padding: "10px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginTop: 4,
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 12,
    color: "#94a3b8",
  },
  generateBtn: {
    marginTop: 12,
    padding: "10px 0",
    background: "linear-gradient(135deg, #4f8ef7 0%, #7c3aed 100%)",
    border: "none",
    borderRadius: 8,
    color: "#fff",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    letterSpacing: "0.02em",
  },
  backBtn: {
    marginTop: 6,
    padding: "8px 0",
    background: "transparent",
    border: "1px solid #334155",
    borderRadius: 8,
    color: "#94a3b8",
    fontSize: 13,
    cursor: "pointer",
  },
  canvasArea: {
    display: "flex",
    gap: 24,
    flexWrap: "wrap",
    flex: 1,
  },
  panel: {
    borderRadius: 10,
    border: "1px solid #1e293b",
    overflow: "hidden",
    flexShrink: 0,
  },
  panelHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 14px",
    background: "#1e293b",
    borderBottom: "1px solid #0f172a",
  },
  panelBadge: {
    background: "#1d4ed8",
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: 4,
    letterSpacing: "0.05em",
  },
  panelTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "#e2e8f0",
  },
  panelSub: {
    fontSize: 11,
    color: "#64748b",
    marginLeft: "auto",
  },

  // ── header nav ───────────────────────────────────────────────
  nav: {
    display:    "flex",
    alignItems: "center",
    gap:        4,
    marginLeft: "auto",
  },
  navTab: {
    padding:       "6px 16px",
    background:    "transparent",
    border:        "none",
    borderRadius:  20,
    color:         "#64748b",
    fontSize:      13,
    fontWeight:    600,
    cursor:        "pointer",
    letterSpacing: "0.02em",
    transition:    "color 0.15s, background 0.15s",
  },
  navTabActive: {
    background: "linear-gradient(135deg, #4f8ef7 0%, #7c3aed 100%)",
    color:      "#fff",
  },
};